# Generated by Django 2.2.16 on 2022-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220519_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='Заголовок транслитом', unique=True, verbose_name='Заголовок транслитом'),
        ),
    ]
