# Generated by Django 2.2.16 on 2022-05-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220519_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
    ]
