# Generated by Django 2.2.16 on 2022-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Рейтинг', max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
    ]
